# Generated by Django 5.0.7 on 2024-08-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunnerUser',
            new_name='Runner',
        ),
    ]
